spring.application.name=projetolivraria
#colocar aqui link do github meu
spring.jpa.open-in-view=true

# Configurações do banco de dados SQL Server
# MELHORIA: Use localhost para garantir que funcione independente do nome da máquina

spring.datasource.url=jdbc:sqlserver://Dell\\SQLEXPRESS:1433;databaseName=bdlivraria;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=4512
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

# Se você também estiver servindo páginas web, pode querer configurar o filtro de codificação de caracteres
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true


# --- ADICIONE ESTE BLOCO NO FINAL DO ARQUIVO ---
# Configurações de Resiliência (HikariCP)
# 1. Testa a conexão toda vez que o sistema for usar o banco
spring.datasource.hikari.test-on-borrow=true

# 2. Query ultra-rápida para verificar se o banco está online
spring.datasource.hikari.connection-test-query=SELECT 1

# 3. Tempo máximo (1 seg) que o sistema espera o banco responder antes de tentar reconectar
spring.datasource.hikari.validation-timeout=1000

